from enum import Enum


class KeyCode(Enum):
    """
    These are the keycodes which work with Surrogate.tv. To check which key
    matches which keycode, see https://keycode.info/ on Chrome.
    """

    KEY_A = "KeyA"
    KEY_B = "KeyB"
    KEY_C = "KeyC"
    KEY_D = "KeyD"
    KEY_E = "KeyE"
    KEY_F = "KeyF"
    KEY_G = "KeyG"
    KEY_H = "KeyH"
    KEY_I = "KeyI"
    KEY_J = "KeyJ"
    KEY_K = "KeyK"
    KEY_L = "KeyL"
    KEY_M = "KeyM"
    KEY_N = "KeyN"
    KEY_O = "KeyO"
    KEY_P = "KeyP"
    KEY_Q = "KeyQ"
    KEY_R = "KeyR"
    KEY_S = "KeyS"
    KEY_T = "KeyT"
    KEY_U = "KeyU"
    KEY_V = "KeyV"
    KEY_W = "KeyW"
    KEY_X = "KeyX"
    KEY_Y = "KeyY"
    KEY_Z = "KeyZ"
    KEY_0 = "Digit0"
    KEY_1 = "Digit1"
    KEY_2 = "Digit2"
    KEY_3 = "Digit3"
    KEY_4 = "Digit4"
    KEY_5 = "Digit5"
    KEY_6 = "Digit6"
    KEY_7 = "Digit7"
    KEY_8 = "Digit8"
    KEY_9 = "Digit9"
    KEY_SHIFT_LEFT = "ShiftLeft"
    KEY_SHIFT_RIGHT = "ShiftRight"
    KEY_CTRL_LEFT = "ControlLeft"
    KEY_CTRL_RIGHT = "ControlRight"
    KEY_ALT_LEFT = "AltLeft"
    KEY_ALT_RIGHT = "AltRight"
    KEY_BACKQUOTE = "Backquote"
    KEY_MINUS = "Minus"
    KEY_EQUAL = "Equal"
    KEY_COMMA = "Comma"
    KEY_PERIOD = "Period"
    KEY_SLASH = "Slash"
    KEY_SEMICOLON = "Semicolon"
    KEY_QUOTE = "Quote"
    KEY_BACKSLASH = "Backslash"
    KEY_BRACKET_LEFT = "BracketLeft"
    KEY_BRACKET_RIGHT = "BracketRight"
    KEY_ARROW_UP = "ArrowUp"
    KEY_ARROW_DOWN = "ArrowDown"
    KEY_ARROW_LEFT = "ArrowLeft"
    KEY_ARROW_RIGHT = "ArrowRight"
    KEY_SPACE = "Space"
